version: '3.8'

services:
  # 后端服务
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: agent-platform-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=agent_platform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./server:/app
    depends_on:
      - postgres
      - redis
      - milvus-standalone
      - minio
    networks:
      - agent-platform-network

  # 前端服务
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: agent-platform-web
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - agent-platform-network

  # PostgreSQL数据库
  postgres:
    image: postgres:14-alpine
    container_name: agent-platform-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agent_platform
    ports:
      - "5432:5432"  # 修改宿主机端口避免冲突
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - agent-platform-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: agent-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - agent-platform-network

  # 使用Milvus独立版本替代整合版本
  milvus-standalone:
    image: milvusdb/milvus:v2.3.5-latest
    container_name: agent-platform-milvus
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - milvus-data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - agent-platform-network

  # 修复etcd配置
  etcd:
    image: bitnami/etcd:latest
    container_name: agent-platform-etcd
    restart: unless-stopped
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      # 移除与命令行冲突的环境变量
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/bitnami/etcd
    networks:
      - agent-platform-network

  # MinIO对象存储
  minio:
    image: minio/minio:latest
    container_name: agent-platform-minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - agent-platform-network

volumes:
  postgres-data:
  redis-data:
  etcd-data:
  minio-data:
  milvus-data:

networks:
  agent-platform-network:
    driver: bridge