app:
  name: agent-platform
  version: 0.1.0
  env: development
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: agent_platform

jwt:
  secret: replace-this-with-a-secure-random-key-in-production
  expiry: 24h
  refresh_expiry: 168h  # 7天

encryption:
  secret: replace-with-a-32-character-secure-key

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

milvus:
  host: localhost
  port: 19530
  user: root
  password: Milvus

model:
  default: gpt-3.5-turbo
  providers:
    - name: openai
      api_key: ${OPENAI_API_KEY}
      base_url: https://api.openai.com/v1
      models:
        - gpt-3.5-turbo
        - gpt-4-turbo
    - name: anthropic
      api_key: ${ANTHROPIC_API_KEY}
      base_url: https://api.anthropic.com
      models:
        - claude-3-opus
        - claude-3-sonnet

storage:
  type: minio
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: agent-platform
  use_ssl: false

logging:
  level: info
  format: json
  output: stdout 